### ISSUE TITLE
Feature request - Convert ARM templates in this repo to Bicep

### ISSUE THREAD

**Issue by o-l-a-v** [scepman/deploy#23]
Microsoft does not seem willing to waste a callory on making ARM tooling for IDEs any better, and tells everyone to author templates using Bicep instead:

* <https://github.com/microsoft/vscode-azurearmtools/issues/1669>

Convert ARM templates in this repo to Bicep to get better tooling and make it easier to contribute with better quality.

**Comment by bb-froggy** [comment]
We decided to stay with ARM, because Bicep internally compiles into ARM before being used and therefore provides us with no additional features; and then the old saying applied "never change a running system".

But point taken ... the world keeps turning, tool support is important, and Bicep seems to be what MS and the community is going for. Moving to Bicep would be a good thing.

**Comment by cleverkm** [comment]
Could you please reconsider this and convert the ARM template to Bicep.
ARM is very hard to read compared to Bicep. Microsoft is putting a lot of effort into Bicep at the time.

**Comment by bb-froggy** [comment]
I agree that it would be a step forward. Support for the ARM toolchain is fading, we are already seeing it in the extra effort required to keep our armttk tests running.

We are currently not well staffed for that task, though, partially due to the summer vacation season. It could take a while till we get to this.
